- hosts: '{{ target }}'
  gather_facts: yes
  become: true
  roles:
    - role: anaconda
      anaconda_install_packages: '-c sotera/spark-sklearn nltk conda-forge/nltk_data matplotlib Networkx seaborn python-louvain numpy'
