---
- name: Update Conda
  command: 'conda update conda -y'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
- name: Disable Conda report_errors 
  command: 'conda config --set report_errors false'
  environment:
    PATH: '{{ anaconda_conda_executable }}'    
- name: Conda install spark_sklearn
  command: 'conda install {{ anaconda_install_spark_sklearn }}'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
- name: Conda install packages
  command: 'conda install {{ anaconda_install_packages }}'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
# - name: Update conda packages
#   command: 'conda update -y --all'
#   environment:
#     PATH: '{{ anaconda_conda_executable }}'
