---
- hosts: '{{ target }}'
  become: true
  tasks:
      - name: conda install packages
        command: 'conda install {{ anaconda_install_packages }}'
        environment:
          PATH: {{ anaconda_conda_executable }}
      - name: Update conda packages
        command: 'conda update -y --all'
        environment:
          PATH: {{ anaconda_conda_executable }}
