---
- name: remove Conda envs
  file:
      path: /opt/cloudera/parcels/Anaconda/envs/py27
      state: absent
- name: remove Conda envs
  file:
      path: /opt/cloudera/parcels/Anaconda/envs/py36
      state: absent      
- name: remove Conda envs
  file:
      path: /opt/cloudera/parcels/Anaconda/envs/py37
      state: absent      
- name: clean Conda
  command: 'conda clean --all -y'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
- name: Update Conda
  command: 'conda update conda -y'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
# - name: Update Conda all
#   command: 'conda update --all -y'
#   environment:
#     PATH: '{{ anaconda_conda_executable }}'    
- name: Disable Conda report_errors 
  command: 'conda config --set report_errors false'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
## Create Python 3.6 and 2.7 env
# - name: Create Conda env python 2.7
#   command: 'conda create -y -n py27 python=2.7'
#   environment:
#     PATH: '{{ anaconda_conda_executable }}'
- name: Create Conda env python 3.7
  command: 'conda create -y -n py37 python=3.7.0'
  environment:
    PATH: '{{ anaconda_conda_executable }}'    
## Install Python 3.6 and 2.7 into envs
- name: Install Python 3.7 in env py37
  command: 'conda install -n py36 python=3.7.0 -y'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
# - name: Install Python 2.7 in env py27
#   command: 'conda install -n py27 python=2.7 -y'
#   environment:
#     PATH: '{{ anaconda_conda_executable }}'    
##
- name: Add channel to Conda
  command: 'conda config --append channels conda-forge'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
# - name: Activate Conda env python 3.6 
#   command: 'conda activate py36'
#   environment:
#     PATH: '{{ anaconda_conda_executable }}'
- name: Conda install spark-nlp
  command: 'conda install {{ anaconda_install_spark_nlp }}'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
- name: Conda install nltk
  command: 'conda install {{ anaconda_install_nltk }}'
  environment:
    PATH: '{{ anaconda_conda_executable }}'
- name: Conda install nltk data
  command: 'conda install {{ anaconda_install_nltk_data }}'
  environment:
    PATH: '{{ anaconda_conda_executable }}'