- hosts: '{{ target }}'
  gather_facts: yes
  become: true
  tasks:
   - name: updating a server
     apt: update_cache=yes
   - name: upgrading a server
     apt:
       upgrade: dist
   - name: Remove dependencies that are no longer required
     apt:
       autoremove: yes
