- name: Restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

