---
# tasks file for kerberos-client

- name: Install the kerberos packages
  package:
     name: krb5-user
     state: present

- name: Copy the client configuration file
  template: src=krb5.conf.j2 dest=/etc/krb5.conf
